### PR TITLE
Changes in home.html animation added

### LINKED ISSUE #97: Improvement in landing page image
Landing page image can be improved and animation can be added. A bit relatable to the club!

### PR DESCRIPTION
**Pull request by sayanp99**
Fixes #97 
@ash1969 @kmAyush 
I have added animation on the landing page image.

### CODE REVIEW

**Comment by kmAyush** [comment]
The animation looks good but the size of the gif file is bit concerning as it will slow down the loading of homepage. Right now the size of homepage including resources is around 2 mb,  If it is possible to keep the size of gif around 400 kb, then it will be a good addition.

**Review by kmAyush — CHANGES_REQUESTED** [review]
If it is possible to compress the gif to size around 400kb or using any other gif whose size is in the limit will be great.

**Comment by foxface-ap** [comment]
@kmAyush bhaiya can we upload GIF somewhere else and then use that link? That way I think it should work.

**Comment by kmAyush** [comment]
> @kmAyush bhaiya can we upload GIF somewhere else and then use that link? That way I think it should work.

For the website to show the gif file on browser, it will be required to download gif on browser. If you upload it somewhere else, it still take same amount of data to show the gif file on page, i guess. If you have any idea to do this in this or other way, let us know it will be appreciated for sure.

**Comment by piedpipr** [comment]
The binary gif file is 21mb! Basically it’s of a higher frame rate. Try reducing the frames and apply compression for web publishing format. If it doesn't get reduced there's no way we can use this huge file.

**Comment by sayanp99** [comment]
I have minimized the gif size to 1.6 MB and further reduction is not possible. Will it be okay?

**Review by kmAyush — APPROVED** [review]

**Comment by kmAyush** [comment]
Be careful while committing, you commit very frequently, avoid unnecessary commits.

**Pull request merged**
