### PR TITLE
Time zone fix

### PR DESCRIPTION
**Pull request by sharshach**
Changed timezone to Asia/kolkatta

Effects of this should be taken place in Ask rec and also at some relevant places

From now onwards IST time is displayed where as UTC is displaying till now

### CODE REVIEW

**Comment by arin17bishwa** [comment]
I think it might be better to use [localtime filter](https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/#std:templatefilter-localtime) instead.  Then the timings will be shown correctly in all time zones.

**Comment by sharshach** [comment]
> I think it might be better to use [localtime filter](https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/#std:templatefilter-localtime) instead.  Then the timings will be shown correctly in all time zones.

Nice idea
You may implement it if it's easy. 
But our client base is completely in India.

**Comment by arin17bishwa** [comment]
Ok vaiya, I will implement it shortly.

**Comment by arin17bishwa** [comment]
Vaiya, I tried out the localtime filter as I had mentioned previously, but it isn't working as intended. Maybe changing the timezone in the settings file is good enough considering that most of the website users are from India only.

 We can also avoid changing the timezone from settings.py file by using  [timezone filter](https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/#std:templatefilter-timezone).

**Comment by sharshach** [comment]
> Vaiya, I tried out the localtime filter as I had mentioned previously, but it isn't working as intended. Maybe changing the timezone in the settings file is good enough considering that most of the website users are from India only.
> 
> We can also avoid changing the timezone from settings.py file by using [timezone filter](https://docs.djangoproject.com/en/3.2/topics/i18n/timezones/#std:templatefilter-timezone).

oh no worries anyway our website is used in india and the current code is working fine. May be we can pick up later for making it better but this is the least priority from our list.

**Pull request merged**
